
Resources:

  SpotFleetIAMRole:
    Type: AWS::IAM::Role
    Condition: CreateMetricsStack
    Properties:
      RoleName: "$(AWS::StackName)-SpotFleetIAMRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AmazonEC2SpotFleetRole"
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: [ spotfleet.amazonaws.com ]
            Action: sts:AssumeRole
      Path: /

  SpotFleet:
    Type: AWS::EC2::SpotFleet
    Properties:
      SpotFleetRequestConfigData:
        IamFleetRole: !GetAtt [SpotFleetIamRole, Arn]
        IamInstanceProfile:
          Arn: !GetAtt [IAMRole, Arn]
        SpotPrice: !Ref SpotPrice
        TargetCapacity: !Ref MinSize
        ImageId: !If [
          "UseDefaultAMI",
          "$(AWSRegion2AMI[$(AWS::Region)][AMI])",
          $(ImageId)
        ]
        LaunchSpecifications:
          - InstanceType: !Ref InstanceType
            SubnetId: !If [ "CreateVpcResources", $(Subnet0), !Select [0, $(Subnets) ]]
            WeightedCapacity: 1
          - InstanceType: !Ref InstanceType
            SubnetId: !If [ "CreateVpcResources", $(Subnet1), !Select [1, $(Subnets) ]]
            WeightedCapacity: 1

  SpotWorkerFleetScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      MaxCapacity: 3
      MinCapacity: 1
      ResourceId: !Sub 'spot-fleet-request/${SpotWorkerFleet}'
      RoleARN: !GetAtt [SpotFleetIamRole, Arn]
      ScalableDimension: 'ec2:spot-fleet-request:TargetCapacity'
      ServiceNamespace: 'ec2'

  FleetUpPolicy:
    Type : "AWS::ApplicationAutoScaling::ScalingPolicy"
    Properties:
      PolicyName: FleetUpPolicy
      PolicyType: StepScaling
      ScalingTargetId: !Ref SpotWorkerFleetScalableTarget
      StepScalingPolicyConfiguration:
        AdjustmentType: ChangeInCapacity
        Cooldown: '1500'
        MetricAggregationType: Average
        StepAdjustments:
          - MetricIntervalUpperBound: 10
            MetricIntervalLowerBound: 0
            ScalingAdjustment: 1
          - MetricIntervalLowerBound: 10
            ScalingAdjustment: 1
